# Configuración del servidor
server.port=8082
server.servlet.context-path=/bitacora
spring.profiles.active=prod

# Configuración básica de JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect
spring.jpa.properties.hibernate.jdbc.time_zone=America/Mexico_City

# Configuración de nombres de tablas
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# Configuración de fechas
spring.jackson.time-zone=America/Mexico_City
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss

# Configuración de logging
logging.level.root=INFO
logging.level.mx.gob.sev=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Configuración para procedimientos almacenados
spring.jpa.properties.hibernate.proc.param_null_passing=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Configuración de conexión JDBC
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5



